apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: ocp-amq-ldap
  name: ocp-amq-ldap
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ocp-amq-ldap:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: develop
      uri: https://github.com/monodot/ocp-amq-ldap
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: amq62-openshift:latest
    type: Source
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
